FROM alpine:3.18

RUN apk update && \
    apk add --no-cache apache2 apache2-utils bash curl && \
    mkdir -p /run/apache2 /var/www/localhost/htdocs

COPY html/ /var/www/localhost/htdocs/

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]